### ISSUE TITLE
Getting errors when running .py1

### ISSUE THREAD

**Issue by smartrickpicks** [aonghena/CoinBot#2]
I have received 38 errors 
"code": "unused-wildcard-import" on various lines, everything installed without errors. Any idea what I did wrong?

Thanks

**Comment by aonghena** [comment]
Hey,

I just put in a code change which should fix that issue. It seemed to be just a lint warning which didn't affect the functionality.

Let me know if you are still having any issues.

**Comment by smartrickpicks** [comment]
Thank you so much!!!
